name: "Run example app"

on: [ workflow_call ]

jobs:
  run_example_app:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Install dependencies
        run: flutter pub get

      - name: Run example app
        run: flutter run example/lib/main.dart